name: Build release

on:
  release:
    types: published

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            executable: ghwiki2chm.exe
          - os: ubuntu-latest
            executable: ghwiki2chm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'

      - name: Install meson and ninja
        run: pip install meson ninja

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: meson setup bin --buildtype release

      - name: Compile
        run: meson compile -C bin

      - name: Create zip
        working-directory: bin
        run: 7z a "../ghwiki2chm-${{ github.ref_name }}-${{ runner.os }}.zip" "${{ matrix.executable }}"

      - name: Upload release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'ghwiki2chm-${{ github.ref_name }}-${{ runner.os }}.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}